// import {UBIType}  from './types';

export const universalBasicIncomeCases = () => {
  return {
    test1: {
      title: 'basic income grant',
      isActive: false,
      label: 'pilot project with basic income grant',
      organization: 'Namibian Basic Income Grant Coalition',
      sample: '2000',
      sampleAge: '25-58',
      funding: 'Protisant Church',
      income: 'US$12',
      incomeType: 'Basic Income',
      effects: '',
      location: 'Nambia, Africa',
      startDate: 'January 2008',
      endDate: 'December 2009',
    },
    test2: {
      title: 'Delhi',
      isActive: true,
      label: 'Universality, Unconditionality, Agency',
      sample: '2000',
      sampleAge: '25-58',
      funding: 'Employed Women’s Association (SEWA)',
      income: 'US $2.20 - $22 / Month',
      incomeType: 'Basic Income',
      effects: '',
      location: 'Delhi, India',
      startDate: 'January 2011',
      endDate: 'Today',
    },
    test3: {
      title: 'Madhya Pradesh',
      isActive: true,
      label: 'Universality, Unconditionality, Agency',
      organization: 'Employed Women’s Association (SEWA)',
      sample: '2000',
      sampleAge: '25-58',
      funding: '',
      income: 'US $2.20 - $22 / Month',
      incomeType: 'Basic Income',
      effects: '',
      location: 'Madhya Pradesh, India',
      startDate: 'January 2008',
      endDate: 'Today',
    },
    test4: {
      title: 'GiveDirectly UBI experiment',
      isActive: true,
      label: 'test in Canada for free $',
      organization: 'GiveDirectly',
      sample: '2000',
      sampleAge: '25-58',
      funding: 'Crowd Sourced',
      income: 'US $0.50 - $1 / day',
      incomeType: 'Basic Income',
      effects: '',
      location: 'Kenya, Africa',
      startDate: '2020',
      endDate: '2032',
    },
    test5: {
      title: 'Finland',
      isActive: false,
      label: 'Basic income for unemployed',
      organization: 'Kela, the Finnish Social Insurance Institution',
      sample: '2000',
      sampleAge: '25-58',
      funding: 'Kela',
      income: 'EU €560 / month',
      incomeType: 'Basic Income',
      effects: '',
      location: 'Finland',
      startDate: 'January 2017',
      endDate: 'December 2018',
    },
    test6: {
      title: 'Negative tax Basic Income',
      isActive: false,
      label: 'Negative tax Basic Income',
      organization: 'Ontario Government',
      sample: '4,000 low-income',
      sampleAge: '18-64',
      funding: 'Ontario Government',
      income: 'US $1000.31 - $1415.27 / month',
      incomeType: 'Basic Income',
      effects: '',
      location: 'Hamilton, Thunder Bay, Lindsay, Ontario, Canada',
      startDate: 'April 2018',
      endDate: 'March 2019',
    },
    test7: {
      title: 'Private UBI',
      isActive: true,
      label: 'Private UBI from Y Combinator',
      organization: 'Y Combinator Research (YCR)',
      sample: '1,000',
      sampleAge: '21-40',
      funding: 'Y Combinator',
      income: 'US $50 - $1,000 / month',
      incomeType: 'Universl Basic Income',
      effects:
        'focus on the impact of UBI on social and physiological well-being—using both subjective and objective measures',
      location: 'Oakland, California, United States',
      startDate: 'April 2019',
      endDate: '2022-2024',
    },
    test8: {
      title: 'Neitherlands Basic Income',
      isActive: false,
      label: 'Neitherlands Basic Income',
      organization: 'Dutch government',
      sample: '2000 welfare recipients',
      sampleAge: '18-64',
      funding: 'Dutch Government',
      income: 'EU €700 / month',
      incomeType: 'Basic Income',
      effects: '“Trust” experiment. primarily to take work if they find it. ',
      location: 'Neitherlands',
      startDate: '2017',
      endDate: '2019',
    },
    test9: {
      title: 'the Stockton Economic Empowerment Demonstration” (SEED)',
      isActive: false,
      label: '',
      organization: '',
      sample: 'TBD',
      sampleAge: 'TBD',
      funding: 'Protisant Church',
      income: 'US $500 / month',
      incomeType: 'Universal Basic Income',
      effects:
        'not to gather rigorous data but to present useful but possibly anecdotal evidence to further UBI politically',
      location: 'Stockton, California',
      startDate: 'TBD',
      endDate: 'TBD',
    },
    test10: {
      title: 'Negative tax Basic Income',
      isActive: false,
      label: 'Negative tax Basic Income',
      organization: '',
      sample: '4,000 low-income',
      sampleAge: '18-64',
      funding: 'Protisant Church',
      income: 'US $1000.31 - $1415.27 / month',
      incomeType: 'Basic Income',
      effects: '',
      location: 'Hamilton, Thunder Bay, Lindsay, Ontario, Canada',
      startDate: 'April 2018',
      endDate: 'March 2019',
    },
    test11: {
      title: 'test',
      isActive: true,
      label: 'test in Canada for free $',
      organization: '',
      sample: '2000',
      sampleAge: '25-58',
      funding: 'Protisant Church',
      income: 'US$12',
      incomeType: 'Basic Income',
      effects: '',
      location: 'Manatoba',
      startDate: '1970',
      endDate: '1972',
    },
  };
};
