
// import {UBIType}  from './types';

export const universalBasicIncomeCases = () => ({
  test1: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test2: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test3: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test4: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test5: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test6: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test7: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test8: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test9: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
test10: {
    title: "test",
    isActive: true,
    label: "test in Canada for free $",
    location: "Manatoba" ,
    startDate: "1970",
    endDate: "1972",
},
});
