// import {UBIType}  from './types';

export const universalBasicIncomeCases = () => ({
  test1: {
    title: 'basic income grant',
    isActive: false,
    label: 'pilot project with basic income grant',
    organization: 'Namibian Basic Income Grant Coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Nambia, Africa',
    startDate: 'January 2008',
    endDate: 'December 2009',
  },
  test2: {
    title: 'Delhi',
    isActive: true,
    label: '1) universality, 2) unconditionality, 3) agency',
    organization: '',
    funding: 'Employed Women’s Association (SEWA)',
    income: 'US $2.20 - $22 / Month',
    location: 'Delhi, India',
    startDate: 'January 2011',
    endDate: 'Today',
  },
  test2b: {
    title: 'Madhya Pradesh',
    isActive: true,
    label: '1) universality, 2) unconditionality, 3) agency',
    organization: 'Employed Women’s Association (SEWA)',
    funding: '',
    income: 'US $2.20 - $22 / Month',
    location: 'Madhya Pradesh, India',
    startDate: 'January 2008',
    endDate: 'Today',
  },
  test3: {
    title: 'test',
    isActive: true,
    label: 'test in Canada for free $',
    organization: 'coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Manatoba',
    startDate: '1970',
    endDate: '1972',
  },
  test4: {
    title: 'test',
    isActive: true,
    label: 'test in Canada for free $',
    organization: 'coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Manatoba',
    startDate: '1970',
    endDate: '1972',
  },
  test5: {
    title: 'test',
    isActive: true,
    label: 'test in Canada for free $',
    organization: 'coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Manatoba',
    startDate: '1970',
    endDate: '1972',
  },
  test6: {
    title: 'test',
    isActive: true,
    label: 'test in Canada for free $',
    organization: 'coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Manatoba',
    startDate: '1970',
    endDate: '1972',
  },
  test7: {
    title: 'test',
    isActive: true,
    label: 'test in Canada for free $',
    organization: 'coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Manatoba',
    startDate: '1970',
    endDate: '1972',
  },
  test8: {
    title: 'test',
    isActive: true,
    label: 'test in Canada for free $',
    organization: 'coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Manatoba',
    startDate: '1970',
    endDate: '1972',
  },
  test9: {
    title: 'test',
    isActive: true,
    label: 'test in Canada for free $',
    organization: 'coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Manatoba',
    startDate: '1970',
    endDate: '1972',
  },
  test10: {
    title: 'test',
    isActive: true,
    label: 'test in Canada for free $',
    organization: 'coalition',
    funding: 'Protisant Church',
    income: 'US$12',
    location: 'Manatoba',
    startDate: '1970',
    endDate: '1972',
  },
});
